alpha: 0.5

m: 0.7

gpu_num: 0

epoch: 300

num_classes: 41

split_ratio: 0.95

batch_size: 64

lr: 0.0001

margin: arcface 


local: False

# load memory to speed training
load_memory: False


fussion: 1


t:        #SupConLoss, default 0.05

ema:     #EMA

alphae: 0.999

ht: basic   #select function

desc: None

seed: 2024
